import type { ZodiacCard } from './cards';

export type CardPrompt = {
  id: string;
  name: string;
  text: string;
};

const promptVariants = [
  {
    id: 'original-male',
    name: 'Original (Male)',
    direction: 'Keep the original concept and depict the character as an adult male.',
  },
  {
    id: 'original-female',
    name: 'Original (Female)',
    direction: 'Keep the original concept and depict the character as an adult female.',
  },
  {
    id: 'special-male',
    name: 'Special (Male)',
    direction: 'Create a special-edition variation with enhanced ceremonial details and a distinctive collector finish; depict the character as an adult male.',
  },
  {
    id: 'special-female',
    name: 'Special (Female)',
    direction: 'Create a special-edition variation with enhanced ceremonial details and a distinctive collector finish; depict the character as an adult female.',
  },
] as const;

const catOriginalPrompts: Record<string, string> = {
  'original-male': [
    'Original face 100%',
    '9:16  VERTICAL ASPECT RATIO,',
    'SLENDER ELONGATED TAROT CARD FORMAT,Celestial Luxury, dark divine aesthetic, elegant mysterious cat goddess frame,',
    'Premium tarot card proportions,',
    '',
    'Male feline deity costume, Eastern Fantasy, Celestial Luxury, dark divine aesthetic, elegant mysterious cat god, predominantly black and deep midnight blue with luminous violet and electric blue accents, luxurious layered outfit with flowing translucent fabrics, intricate celestial embroidery and glowing star motifs.',
    'Upper body: sleeveless high-neck black fitted tunic, structured and elegant, made from luxurious matte black fabric, subtle satin texture, fitted closely around the torso, decorated with delicate silver chains, celestial star ornaments and glowing blue-violet crystal pendants across the chest. High collar partially covering the neck, layered black-and-silver necklaces with a large four-point celestial star crystal pendant at the center.',
    'Shoulder and arms: long detached translucent sleeves attached around the upper arms, extremely wide and flowing, made from sheer black fabric layered with translucent deep-violet panels, sharp elongated fabric tips resembling feline claws, decorated with silver celestial embroidery, tiny glowing stars and crystal ornaments. Black fitted gloves extending over the hands, decorated with luminous claw-like crystal tips, giving the appearance of magical feline claws.',
    'Waist: elaborate black waist belt composed of multiple layered leather and metallic straps, decorated with silver chains, dangling celestial charms, small blue-violet crystals and star-shaped ornaments. Several long decorative chains hang asymmetrically from the waist and hips, creating elegant movement.',
    'Lower body: extremely wide flowing black hakama-style trousers / palazzo pants, layered and voluminous, high-waisted, loose silhouette, gathered slightly around the ankles. Luxurious black fabric with subtle blue-violet sheen. The outer edges feature intricate silver celestial embroidery, tiny stars and feline-inspired ornamental patterns.',
    'Outer layer: long asymmetrical translucent ceremonial robe panels flowing from the shoulders and waist, black transparent fabric mixed with deep sapphire-blue and violet layers, long pointed tails of fabric, delicate silver borders, glowing constellation patterns and scattered luminous stars. The fabric should trail dramatically behind the character like a celestial aura.',
    'Footwear: elegant black high-top divine boots, armored leather construction, decorated with silver metal details, blue-violet glowing crystals and celestial patterns. Thick elevated soles, sharp elegant silhouette. Toes feature subtle feline claw-shaped armor, creating the impression of supernatural cat paws without becoming literal animal feet.',
    'Cat features integrated into the outfit: elegant black feline ears with glowing blue-violet inner ears, long luxurious black cat tail with a subtle luminous constellation pattern running along the fur, several tiny glowing star-shaped markings embedded into the fur, magical feline claws glowing faintly blue-violet.',
    'Accessories: layered silver-black celestial necklaces, star-shaped crystal pendants, delicate chains crossing the chest, crystal earrings, small celestial charms hanging from the waist, silver rings, black gemstone bracelets, glowing blue-violet crystals, constellation ornaments, feline-moon insignia.',
    'Color palette: obsidian black, midnight blue, deep sapphire, royal violet, silver, luminous electric blue, subtle white highlights.',
    'Materials: matte black silk, satin, sheer chiffon, translucent organza, leather, dark metal, polished silver, luminous crystals, enchanted fabric.',
    'Overall design: elegant, mysterious, regal, seductive but dignified, supernatural feline deity, celestial priest-warrior aesthetic, luxurious Eastern fantasy costume, highly detailed embroidery, layered flowing fabrics, asymmetrical design, sophisticated silhouette, no modern clothing, no casual elements.',
    'Exact pose reference, preserve the same body posture and limb placement: low kneeling crouch, one knee on the ground and the opposite knee raised, raised leg forming a strong angular shape, torso slightly leaning forward and twisted toward camera, one arm lifted behind the head gripping a sword handle, sword laid horizontally across the shoulders, opposite elbow bent with hand resting on the raised thigh, head slightly lowered, shoulders asymmetrical, dynamic diagonal body line, grounded stable posture, full body visible, no standing pose, no sitting chair, no symmetrical pose.',
    '',
    'Background:',
    '- Full moon in night sky',
    '- Ruins / gothic architecture',
    '- Hanging crystal chains / star ornaments',
    '- Water surface with reflections',
    '- Mist / fog / clouds',
    '- Blue and purple lighting',
    '- Fantasy, celestial, mystical atmosphere',
  ].join('\n'),
  'original-female': [
    'Original face 100%',
    '9:16  VERTICAL ASPECT RATIO,',
    'SLENDER ELONGATED TAROT CARD FORMAT,Celestial Luxury, dark divine aesthetic, elegant mysterious cat goddess frame,',
    'Premium tarot card proportions,',
    '',
    'Female feline deity costume, Eastern Fantasy, Celestial Luxury, dark divine aesthetic, elegant mysterious cat goddess, predominantly black and deep midnight blue with luminous violet and electric blue accents. Luxurious, feminine two-piece outfit featuring a stylish cropped top, a short elegant mini skirt, and long thigh-high divine boots. Intricate celestial embroidery, glowing star motifs, luxurious layered fabrics and flowing translucent elements.',
    '',
    'Upper body - Cropped top:',
    'Elegant sleeveless black cropped top with a high neckline, ending just above the waist to reveal a tasteful portion of the midriff. Feminine, sophisticated and form-fitting silhouette, tailored closely around the bust and waist. Luxurious matte black fabric with subtle satin texture and structured panels emphasizing the natural waistline. Decorated with delicate silver chains, celestial star ornaments and glowing blue-violet crystal pendants across the chest. High collar partially covering the neck. Layered black-and-silver necklaces with a large four-point celestial star crystal pendant centered at the upper chest. The cropped top should look regal, luxurious and elegant, combining traditional Eastern fantasy aesthetics with a modern fantasy silhouette.',
    '',
    'Shoulders and arms:',
    'Long detached translucent sleeves attached around the upper arms, extremely wide and flowing, made from sheer black chiffon layered with translucent deep-violet and sapphire-blue panels. Sleeves taper into sharp elongated fabric tips resembling elegant feline claws. Decorated with silver celestial embroidery, tiny glowing stars and crystal ornaments. Elegant black fitted gloves extending over the hands, decorated with luminous claw-like crystal tips, creating the appearance of magical feline claws.',
    '',
    'Waist:',
    'Exposed feminine midriff with a clearly defined waist. An elaborate black celestial corset-style waist belt sits around the waist, composed of layered leather and metallic straps. Decorated with polished silver chains, dangling celestial charms, small blue-violet crystals and star-shaped ornaments. Several long decorative chains hang asymmetrically from the waist and hips, creating graceful movement. The waist belt emphasizes a refined hourglass silhouette and complements the cropped top.',
    '',
    'Lower body - Short mini skirt:',
    'Elegant high-waisted black celestial mini skirt with a short hemline ending at the upper thighs. Feminine, fitted silhouette that accentuates the waist and hips while maintaining a regal fantasy aesthetic. Luxurious layered black silk and satin fabric with subtle midnight-blue and violet sheen. The skirt features an asymmetrical design, with one side slightly longer than the other, decorated with intricate silver celestial embroidery, tiny stars, crescent-moon motifs and subtle feline-inspired ornamental patterns. Delicate metallic silver trims and small luminous blue-violet crystals embellish the waistband and skirt edges.',
    'The mini skirt should be clearly visible and remain short, with no long trousers underneath. Add delicate overlapping translucent fabric panels hanging asymmetrically from the hips, flowing gracefully behind the character without covering the main short skirt. The design should be elegant, stylish and feminine, combining a short skirt with luxurious celestial decorations.',
    '',
    'Outer ceremonial layer:',
    'Long asymmetrical translucent ceremonial robe panels flowing from the shoulders, waist and hips. Black transparent fabric mixed with deep sapphire-blue and violet layers. Long pointed fabric tails extending dramatically behind the character like a celestial aura. Delicate silver borders, glowing constellation patterns, tiny luminous stars and moon motifs. The fabric should float and trail naturally as if affected by magical energy. The robe panels should frame the body and leave the cropped top, exposed waist and short mini skirt clearly visible.',
    '',
    'Footwear - Thigh-high boots:',
    'Elegant black feminine thigh-high divine boots extending above the knees, reaching the upper thighs. Sleek, form-fitting silhouette with luxurious armored leather construction, emphasizing the length and elegance of the legs. High-quality matte black leather with subtle satin highlights, intricate silver metallic details, glowing blue-violet crystals and elaborate celestial patterns. Refined high heels with elegant proportions and sturdy fantasy-inspired construction. The boots feature delicate silver embroidery, crescent-moon ornaments and subtle feline claw-shaped armor around the toes. Intricate silver buckles and decorative straps wrap elegantly around the ankles and upper calves. Glowing celestial runes and small blue-violet crystals are embedded along the sides of the boots. The boots should be tall, luxurious and clearly visible, extending well above the knees, creating a striking divine warrior aesthetic.',
    '',
    'Cat features integrated into the character:',
    'Elegant black feline ears positioned naturally on the head, with glowing blue-violet inner ears. Long luxurious black cat tail emerging naturally from the lower back, covered in soft detailed fur with a subtle luminous constellation pattern running along its length. Several tiny glowing star-shaped markings embedded into the fur. Elegant magical feline claws with faint blue-violet luminescence.',
    '',
    'Accessories:',
    'Layered silver-black celestial necklaces, star-shaped crystal pendants, delicate chains crossing the chest and waist, crystal earrings, crescent-moon earrings, small celestial charms hanging from the waist, silver rings, black gemstone bracelets, glowing blue-violet crystals, constellation ornaments and a refined feline-moon insignia.',
    '',
    'Hair integration:',
    'Long luxurious flowing black hair with subtle midnight-blue and violet highlights, soft layered strands framing the face and flowing naturally behind the body. Hair ornaments made from silver celestial metal and small glowing blue-violet crystals, harmonizing with the feline deity aesthetic.',
    '',
    'Color palette:',
    'Obsidian black, midnight blue, deep sapphire, royal violet, silver, luminous electric blue, subtle white highlights.',
    '',
    'Materials:',
    'Matte black silk, satin, sheer chiffon, translucent organza, layered velvet, leather, dark metal, polished silver, luminous crystals, enchanted celestial fabric.',
    '',
    'Overall design:',
    'Elegant, mysterious, regal, feminine, alluring but dignified, supernatural feline goddess, celestial priestess-warrior aesthetic, luxurious Eastern fantasy costume. A stylish black cropped top revealing the midriff, a short asymmetrical mini skirt and elegant thigh-high black divine boots are the defining features of the outfit. Highly detailed embroidery, layered flowing fabrics, sophisticated feminine silhouette, defined waist, exposed midriff, long elegant legs, dramatic translucent fabric movement, divine and otherworldly presence. Full-body character design, realistic anatomy, exquisite costume details, cinematic lighting, highly detailed textures, no modern casual clothing, no long trousers, no long skirt, no literal animal costume, no exaggerated cartoon proportions.',
    '',
    'Pose:',
    '- Crouching/kneeling on rock',
    '- One knee up, one knee down',
    '- One hand resting on the rock, fingers spread',
    '- Head slightly tilted down, looking to the side',
    '- Long hair flowing down, covering part of the body',
    '- Dramatic, powerful, mysterious, elegant pose',
    '',
    'Background, SCENE:',
    '- Full moon in night sky',
    '- Ruins / gothic architecture',
    '- Hanging crystal chains / star ornaments',
    '- Water surface with reflections',
    '- Mist / fog / clouds',
    '- Blue and purple lighting',
    '- Fantasy, celestial, mystical atmosphere',
  ].join('\n'),
};

const dogOriginalPrompts: Record<string, string> = {
  'original-male': [
    'Original face 100%',
    '',
    'VERTICAL ASPECT RATIO,',
    'SLENDER ELONGATED TAROT CARD FORMAT,Celestial Luxury, dark divine aesthetic, elegant mysterious dog goddess frame, borders card, dog zodiac,',
    'Premium tarot card proportions,',
    '',
    'Male dark fantasy assassin, muscular handsome male warrior with a dark gothic aesthetic, no hood covering the head, wearing a black sleeveless gothic assassin outfit with a long black cloak draped over the shoulders, black pointed dog ears with soft black fur and subtle gray inner fur, long thick fluffy black dog tail with dark gray and silver-white tip, black sleeveless fitted top exposing a muscular chest and broad shoulders, black leather cross-body harness, multiple black tactical belts and straps around the waist, silver rings and hanging metallic ornaments across the chest, black fingerless gloves, layered black leather arm wraps, heavy black armored bracers with sharp silver metallic edges, asymmetrical long black layered robe with multiple overlapping fabric panels, long flowing black coat extending to the ankles, dark charcoal fabric, silver buckles, black tactical trousers, black armored boots, an ivory-white bone skull mask with a wide jaw, sharp jagged teeth and multiple elongated fangs attached to the waist as an accessory, intricate leather textures, dark medieval fantasy assassin clothing, mysterious powerful warrior appearance, elegant dark gothic design, black and charcoal color palette, full body, front view, highly detailed anime character concept art.',
    '',
    'POSE & BODY LANGUAGE:',
    'Dynamic low-angle perspective, character crouching on an elevated rooftop ledge, one knee raised prominently toward the camera, one leg bent and resting on the ledge, the other leg folded beneath the body, leaning slightly forward, one arm resting casually on the raised knee, the other arm hanging loosely downward toward the foreground, relaxed but intimidating posture, head slightly tilted downward, looking directly at the viewer, dominant and confident body language, dramatic foreshortening, strong perspective distortion, one oversized combat boot prominently positioned in the foreground.',
    '',
    'CAMERA & COMPOSITION:',
    'Vertical 9:16 composition, full-body character illustration, dramatic low-angle shot, slightly tilted camera perspective, close foreground perspective, cinematic framing, character occupying most of the frame, strong depth of field, foreground ledge partially obscuring the lower body, detailed silhouette, dynamic asymmetrical composition.',
    '',
    'BACKGROUND:',
    'Dark cyberpunk urban alley at night, industrial rooftop environment, rough concrete and dark brick walls, futuristic city architecture, dense tropical foliage and large palm leaves silhouetted against the background, bright neon yellow-green light source behind the character, glowing geometric light panels, scattered neon reflections, dark industrial structures, atmospheric urban decay, subtle floating dust particles, deep shadows, mysterious dystopian atmosphere.',
    '',
    'LIGHTING & COLOR PALETTE:',
    'High-contrast cinematic lighting, intense neon lime green and electric yellow backlighting, dramatic rim light outlining the character\'s hair, dog ears, shoulders and clothing, subtle cool gray highlights, deep black shadows, luminous yellow-green reflections on metallic accessories, moody ambient lighting, strong contrast between bright background and dark character silhouette.',
    '',
    'ART STYLE & RENDERING:',
    'High-quality anime illustration, semi-realistic anime character design, dark cyberpunk aesthetic, gothic street fashion, intricate clothing details, clean sharp line art, detailed hair strands, realistic fabric folds, highly detailed tactical accessories, polished cel shading, subtle painterly shading, dramatic cinematic atmosphere, professional character concept art, highly detailed, crisp focus, masterpiece.',
    '',
    'MOOD & ATMOSPHERE:',
    'Mysterious, rebellious, confident, intimidating, nocturnal, dark futuristic aesthetic, elegant cyberpunk antihero, edgy gothic fashion.',
    '',
    'NEGATIVE PROMPT:',
    'low quality, blurry, low resolution, bad anatomy, malformed hands, extra fingers, missing fingers, extra limbs, duplicated body parts, distorted face, asymmetrical eyes, deformed legs, incorrect joints, stiff pose, flat lighting, washed-out colors, bright pastel palette, excessive highlights, messy composition, cropped head, cropped ears, missing tail, missing dog ears, missing ivory-white skull mask at waist, missing neon accents, text, watermark, logo.',
  ].join('\n'),
  'original-female': [
    'Original face 100%',
    '',
    'VERTICAL ASPECT RATIO,',
    'SLENDER ELONGATED TAROT CARD FORMAT,Celestial Luxury, dark divine aesthetic, elegant mysterious dog goddess frame, borders card, dog zodiac,',
    'Premium tarot card proportions,',
    '',
    'Female dark fantasy assassin, beautiful tall athletic female warrior with an elegant yet intimidating dark gothic aesthetic, no hood covering the head, wearing a long black gothic cloak draped over the shoulders, black pointed dog ears with soft black fur and subtle gray inner fur, long fluffy black dog tail with dark gray and silver-white tip, fitted black sleeveless gothic top with a deep neckline, exposed midriff and bare shoulders, black leather cross-body harness and chest straps, multiple silver rings and hanging metallic ornaments, black leather arm sleeves, black fingerless gloves, layered black leather belts and tactical straps around the waist and hips, silver buckles and hanging dagger-shaped accessories, asymmetrical long black skirt with multiple overlapping fabric layers, high side slits exposing the thighs, long flowing black cloak panels, fitted black shorts underneath, dark armored thigh accessories, black and silver armored forearm guards, black knee-high boots with pointed armored details, an ivory-white bone skull mask with a wide jaw, sharp jagged teeth and multiple elongated fangs attached to the waist as an accessory, intricate leather textures, dark charcoal and black fabric, medieval fantasy assassin clothing, mysterious elegant silhouette, black and charcoal color palette, full body, front view, highly detailed anime character concept art.',
    '',
    'POSE & BODY LANGUAGE:',
    'Dynamic low-angle perspective, character crouching on an elevated rooftop ledge, one knee raised prominently toward the camera, one leg bent and resting on the ledge, the other leg folded beneath the body, leaning slightly forward, one arm resting casually on the raised knee, the other arm hanging loosely downward toward the foreground, relaxed but intimidating posture, head slightly tilted downward, looking directly at the viewer, dominant and confident body language, dramatic foreshortening, strong perspective distortion, one oversized combat boot prominently positioned in the foreground.',
    '',
    'CAMERA & COMPOSITION:',
    'Vertical 9:16 composition, full-body character illustration, dramatic low-angle shot, slightly tilted camera perspective, close foreground perspective, cinematic framing, character occupying most of the frame, strong depth of field, foreground ledge partially obscuring the lower body, detailed silhouette, dynamic asymmetrical composition.',
    '',
    'BACKGROUND:',
    'Dark cyberpunk urban alley at night, industrial rooftop environment, rough concrete and dark brick walls, futuristic city architecture, dense tropical foliage and large palm leaves silhouetted against the background, bright neon yellow-green light source behind the character, glowing geometric light panels, scattered neon reflections, dark industrial structures, atmospheric urban decay, subtle floating dust particles, deep shadows, mysterious dystopian atmosphere.',
    '',
    'LIGHTING & COLOR PALETTE:',
    'High-contrast cinematic lighting, intense neon lime green and electric yellow backlighting, dramatic rim light outlining the character\'s hair, dog ears, shoulders and clothing, subtle cool gray highlights, deep black shadows, luminous yellow-green reflections on metallic accessories, moody ambient lighting, strong contrast between bright background and dark character silhouette.',
    '',
    'ART STYLE & RENDERING:',
    'High-quality anime illustration, semi-realistic anime character design, dark cyberpunk aesthetic, gothic street fashion, intricate clothing details, clean sharp line art, detailed hair strands, realistic fabric folds, highly detailed tactical accessories, polished cel shading, subtle painterly shading, dramatic cinematic atmosphere, professional character concept art, highly detailed, crisp focus, masterpiece.',
    '',
    'MOOD & ATMOSPHERE:',
    'Mysterious, rebellious, confident, intimidating, nocturnal, dark futuristic aesthetic, elegant cyberpunk antihero, edgy gothic fashion.',
    '',
    'NEGATIVE PROMPT:',
    'low quality, blurry, low resolution, bad anatomy, malformed hands, extra fingers, missing fingers, extra limbs, duplicated body parts, distorted face, asymmetrical eyes, deformed legs, incorrect joints, stiff pose, flat lighting, washed-out colors, bright pastel palette, excessive highlights, messy composition, cropped head, cropped ears, missing tail, missing dog ears, missing ivory-white skull mask at waist, missing neon accents, text, watermark, logo.',
  ].join('\n'),
};

const goatOriginalPrompt: Record<string, string> = {
  'original-male': '',
  'original-female': [
    'Original face 100%',
    '',
    '9:16  VERTICAL ASPECT RATIO,',
    'SLENDER ELONGATED TAROT CARD FORMAT,Celestial Luxury, dark divine aesthetic, elegant mysterious goddess frame,',
    'Premium tarot card proportions,',
    '',
    '1 adult female sheep demoness, original character, beautiful mature anime girl, long voluminous hair with messy layered bangs, fluffy wavy hair flowing down to her thighs, large curved black ram horns with dark reddish-brown markings, long pointed sheep ears, pale porcelain skin, glowing eyes, subtle eyes makeup, delicate facial features, confident and slightly seductive smile, red tribal markings on her face, shoulders, arms, abdomen and thighs.',
    'Wearing a luxurious black and crimson red dark fantasy warrior outfit, black leather strappy crop top with a plunging neckline, black choker with intricate metal details, exposed midriff, red tribal tattoos covering her body, asymmetrical black and red short skirt with a long rectangular red front panel, intricate black geometric rune symbols embroidered on the fabric, wide black leather belt with multiple buckles and metal rings, layered black fabric, dark fur trims around the wrists, shoulders, waist and boots, black thigh-high boots with fur cuffs, open-toe sandals, elaborate gothic accessories, red dangling earrings, intricate leather straps and silver metal ornaments.',
    'Holding an enormous double-bladed fantasy battle axe with one hand, extremely long black and dark crimson shaft, massive dark steel axe head, glowing red rune symbols engraved on the blade, ornate gothic weapon design, sharp metallic edges, intricate red decorations, imposing heavy weapon.',
    'Full-body standing character, confident and relaxed warrior stance, holding a giant battle axe vertically beside her body with one hand, one leg slightly bent, weight shifted onto one leg, shoulders relaxed, body facing forward, head slightly tilted, looking directly at the viewer, confident seductive expression, long flowing hair and fur moving gently, elegant yet powerful presence.',
    '',
    'Background:',
    'Dark mystical fantasy temple, gothic architecture, enormous black stone pillars, dark crimson banners, ancient geometric runes, mysterious demonic symbols, floating red embers, subtle smoke, atmospheric dark fantasy environment, dramatic cinematic lighting, faint red magical glow, dark charcoal and crimson color palette.',
    '',
    'Art Style & Rendering:',
    'High-quality semi-realistic anime illustration, detailed fantasy character concept art, elegant dark fantasy aesthetic, refined line art, realistic anatomy, beautiful facial details, intricate costume design, highly detailed fabric textures, realistic leather and metal materials, soft painterly shading, dramatic cinematic lighting, subtle rim lighting, high contrast, sophisticated composition, premium collectible fantasy character art, ultra-detailed, 8K quality.',
    '',
    'Color Palette:',
    'Crimson red, deep black, charcoal gray, dark burgundy, ivory white, muted silver, subtle warm highlights.',
    '',
    'Composition & Quality:',
    'Vertical 9:16 aspect ratio, full-body character prominently displayed, centered composition, tall elegant proportions, detailed character reference sheet, sharp focus, consistent character design, professional fantasy artbook presentation, masterpiece.',
    '',
    'Negative Prompt:',
    'Panels, quality, blurry, pixelated, bad anatomy, extra limbs, extra fingers, missing fingers, malformed hands, deformed face, asymmetrical eyes, short hair, missing horns, missing ears, incorrect weapon, duplicated character, inconsistent outfit, poorly drawn details, cropped feet, cropped head, text, watermark, logo.',
  ].join('\n'),
};

export function getCardPrompts(card: ZodiacCard): CardPrompt[] {
  const availableVariants = card.id === 'cat' || card.id === 'goat'
    ? promptVariants.slice(0, 2)
    : card.id === 'dog'
      ? promptVariants.filter(variant => variant.id in dogOriginalPrompts)
      : promptVariants;
  return availableVariants.map(variant => ({
    id: variant.id,
    name: variant.name,
    text: card.id === 'cat'
      ? catOriginalPrompts[variant.id]
      : card.id === 'dog'
        ? dogOriginalPrompts[variant.id]
        : card.id === 'goat'
          ? goatOriginalPrompt[variant.id]
          : `${card.imagePrompt}\n\n${variant.direction}`,
  }));
}